stages:
  - publish
  - deploy
  - release
compile:
  stage: publish
  image: gitlab-registry.cern.ch/rvalverd/eos_exporter:latest
  script:
    - |
      # compile eos_exporter
      mkdir public
      make rpm
      cp *.rpm public

  retry: 1
  artifacts:
    name: eos_exporter_"$CI_COMMIT_REF_NAME"
    paths:
      - eos_exporter
    expire_in: 1 week
    when: on_success
    public: true
#    rules:
#    - if: $CI_COMMIT_TAG

deployment:
  stage: deploy
  # Execute only on tag on master
#  only:
#    - tags
  rules:
    - if: $CI_COMMIT_BRANCH == 'gl-ci-test'
#  except:
#    - branches
  image: gitlab-registry.cern.ch/ci-tools/ci-web-deployer:latest
  script:
    - |
      echo "ssh -o StrictHostKeyChecking=no -o GSSAPITrustDns=yes -o GSSAPIAuthentication=yes -o GSSAPIDelegateCredentials=yes $EOS_ACCOUNT_USERNAME@lxplus.cern.ch createrepo --update $EOS_PATH" >> /sbin/deploy-eos-xrdcp.sh
      deploy-eos
