stages:
  - publish
compile:
  stage: publish
  script:
    - make build
  image: golang:1.17
  retry: 2
  artifacts:
    name: eos_exporter_"$CI_COMMIT_REF_NAME"
    paths:
      - eos_exporter
    expire_in: 1 week
    when: on_success
    public: true
#    rules:
#    - if: $CI_COMMIT_TAG
