stages:
  - build:rpm
  - publish
  
.build_eos-exporter-template: &build_eos-exporter_definition
  stage: build:rpm
  script:
    - ${PKG_MGR} install -y golang rpm-devel rpm-build make rpmdevtools sudo createrepo git
    - make rpm
    - mkdir -p ${CI_JOB_NAME}_artifacts
    - cp --recursive rpmbuild/SRPMS/ ${CI_JOB_NAME}_artifacts
    - cp --recursive rpmbuild/RPMS/ ${CI_JOB_NAME}_artifacts
  artifacts:
    paths:
      - ${CI_JOB_NAME}_artifacts
    expire_in: 1 week

el-7:
  image: gitlab-registry.cern.ch/linuxsupport/cc7-base
  stage: build:rpm
  script:
    - yum-config-manager --save --setopt=epel.baseurl=https://linuxsoft.cern.ch/internal/archive/epel/7/x86_64/ 
    - yum install -y sudo sssd-client createrepo tree
    - tree
    - yum install -y golang rpm-devel rpm-build make rpmdevtools sudo createrepo git
    - make rpm
    - mkdir -p ${CI_JOB_NAME}_artifacts
    - cp --recursive rpmbuild/SRPMS/ ${CI_JOB_NAME}_artifacts
    - cp --recursive rpmbuild/RPMS/ ${CI_JOB_NAME}_artifacts
el-8:
  image: gitlab-registry.cern.ch/linuxsupport/alma8-base
  variables:
    PKG_MGR: dnf
  extends: .build_eos-exporter-template

el-9:
  image: gitlab-registry.cern.ch/linuxsupport/alma9-base
  variables:
    PKG_MGR: dnf
  extends: .build_eos-exporter-template

rpm_artifacts:
  stage: publish
  image: gitlab-registry.cern.ch/linuxsupport/cc7-base
  script:
    - yum-config-manager --save --setopt=epel.baseurl=https://linuxsoft.cern.ch/internal/archive/epel/7/x86_64/ 
    - yum install -y sudo sssd-client createrepo tree
    - tree
    - sudo -u stci -H ./gitlab-ci/publish_rpms.sh
  needs:
    - job: el-7
    - job: el-8
    - job: el-9
  tags:
    - docker-node
  retry: 2
  when: manual
  only:
    - tags
