stages:
  - publish
  - deploy
compile:
  stage: publish
  image: centos:7
  script:
    - |
      yum install -y epel-release && yum update -y && yum install -y golang && yum groupinstall -y "Development Tools"
      
      # install git from source, as the one in the centos repo is too old
      yum -y install epel-release
      yum -y groupinstall "Development Tools"
      yum -y install wget perl-CPAN gettext-devel perl-devel  openssl-devel  zlib-devel curl-devel expat-devel  getopt asciidoc xmlto docbook2X
      ln -s /usr/bin/db2x_docbook2texi /usr/bin/docbook2x-texi

      yum -y install wget
      export VER="2.32.0"
      wget https://github.com/git/git/archive/v${VER}.tar.gz
      tar -xvf v${VER}.tar.gz
      rm -f v${VER}.tar.gz
      cd git-*
      make configure
      ./configure --prefix=/usr
      make
      make install
      cd ..
      
      # compile eos_exporter
      mkdir public
      make rpm
      cp *.rpm public

  retry: 1
  artifacts:
    name: eos_exporter_"$CI_COMMIT_REF_NAME"
    paths:
      - eos_exporter
    expire_in: 1 week
    when: on_success
    public: true
#    rules:
#    - if: $CI_COMMIT_TAG

deployment:
  stage: deploy
  # Execute only on tag on master
  only:
    - tags
  except:
    - branches
  image: gitlab-registry.cern.ch/ci-tools/ci-web-deployer:latest
  script:
    - |
      echo "ssh -o StrictHostKeyChecking=no -o GSSAPITrustDns=yes -o GSSAPIAuthentication=yes -o GSSAPIDelegateCredentials=yes $EOS_ACCOUNT_USERNAME@lxplus.cern.ch createrepo --update $EOS_PATH" >> /sbin/deploy-eos-xrdcp.sh
      deploy-eos

