stages:
        - publish
compile:
        stage: publish
        script:
                - yum install -y golang
                - make build
release:
        stage: publish
        image: gitlab-registry.cern.ch/linuxsupport/cc7-base
#        script:
#                - yum install -y golang
        tags:
                - docker-cc7
        retry: 2
        only:
                - tags@eos_exporter

