{
 "title": "EOS HPM Instance",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "label_values(eosinstance)" } }
  ]
 },
 "panels": [
  {
   "title": "EOS Version",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "FST VERSION",
     "type": "stat",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(eos_version)(eos_node_info{cluster=\"eos${instance}\"})",
       "legendFormat": "{{eos_version}}"
      },
      {
       "expr": "sum by(xrootd_version)(eos_node_info{cluster=\"eos${instance}\"})",
       "legendFormat": "{{xrootd_version}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Alerts ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    { "title": "ALERTS", "type": "alertlist", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 } }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Health",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(eos_fs_boot_status{cluster=\"eos$instance\"} != 0 and eos_fs_config_status != 3) > 0 or vector(0)",
     "legendFormat": "FS Boot Status"
    },
    {
     "expr": "count(eos_recyle_used_bytes{cluster=\"eos$instance\"} / eos_recycle_max_bytes{cluster=\"eos$instance\"} > 0.8) or vector(0)",
     "legendFormat": "Recycle bin"
    },
    {
     "expr": "count(eos_group_statfs_filled_avg{cluster=\"eos$instance\"} > 80) or vector(0)",
     "legendFormat": "Group Fill Status"
    },
    {
     "expr": "count(eos_group_statfs_filled_dev{cluster=\"eos$instance\"} > 75) or vector(0)",
     "legendFormat": "Group Dev Status"
    },
    {
     "expr": "count((sum by(node)(eos_fs_statfs_usedbytes{cluster=\"eos$instance\"})/sum by(node)(eos_fs_statfs_sizebytes{cluster=\"eos$instance\"})) > 0.80) or vector(0)",
     "legendFormat": "Node Fill Status"
    },
    {
     "expr": "count(eos_space_statfs_freebytes{cluster=\"eos$instance\", space=\"default\"}/eos_space_statfs_sizebytes{cluster=\"eos$instance\", space=\"default\"} < 0.3) or vector(0)",
     "legendFormat": "Free Space"
    },
    { "legendFormat": "Free Space" },
    {
     "expr": "count(100 - (avg by (instance) (rate(node_cpu_seconds_total{eosinstance=\"$instance\", role=\"storage\", mode=\"idle\"}[1m])) * 100)>90) or vector(0)",
     "legendFormat": "FST Load"
    },
    {
     "expr": "count(1-(node_memory_MemAvailable_bytes/node_memory_MemTotal_bytes{eosinstance=\"$instance\", role=\"storage\"}) > 0.9) or vector(0)",
     "legendFormat": "FST Memory"
    },
    {
     "expr": "(eos_space_cfg_balancer_status{cluster=\"eoshome-i01\", space=\"default\"} == 0) or vector(0)",
     "legendFormat": "Balancer Enabled"
    },
    {
     "expr": "count(up{job=\"node\", eosinstance=\"$instance\"} == 0) > 0 or vector(0) ",
     "legendFormat": "Node Up"
    },
    {
     "expr": "avg(node_time_seconds{job=\"node\", eosinstance=\"$instance\", role=\"storage\"} - node_boot_time_seconds{job=\"node\", eosinstance=\"$instance\", role=\"storage\"}) > 20736000 or vector(0)",
     "legendFormat": "FST Uptime"
    }
   ]
  },
  {
   "title": "Files",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eos_ns_files_total{cluster=\"eos$instance\"}"
    }
   ]
  },
  {
   "title": "Directories",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eos_ns_dirs_total{cluster=\"eos$instance\"}"
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(eos_space_statfs_sizebytes_configrw{cluster=\"eos$instance\"})"
    }
   ]
  },
  {
   "title": "Used Space",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(eos_space_statfs_usedbytes{cluster=\"eos$instance\"})"
    }
   ]
  },
  {
   "title": "Free",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(eos_space_statfs_freebytes{cluster=\"eos$instance\"})"
    }
   ]
  },
  {
   "title": "Used Space ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eos_space_statfs_usedbytes{cluster=\"eos$instance\", space=\"default\"}/eos_space_statfs_sizebytes{cluster=\"eos$instance\", space=\"default\"}"
    }
   ]
  },
  {
   "title": "Difference",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(eos_space_statfs_usedbytes{cluster=\"eos$instance\"})"
    }
   ]
  },
  {
   "title": "Avg disk fill",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(eos_fs_statfs_usedbytes{cluster=\"eos$instance\"}/eos_fs_statfs_sizebytes{cluster=\"eos$instance\"})"
    }
   ]
  },
  {
   "title": "Avg Group Fill",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(eos_group_statfs_filled_avg{cluster=\"eos$instance\"})"
    }
   ]
  },
  {
   "title": "Writers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(eos_space_disk_wopen{cluster=\"eos$instance\"})"
    }
   ]
  },
  {
   "title": "Readers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(eos_space_disk_ropen{cluster=\"eos$instance\"})"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(eos_space_disk_iops_configrw{cluster=\"eos$instance\"})"
    }
   ]
  },
  {
   "title": "Write Throughput",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(eos_space_disk_writeratemb{cluster=\"eos$instance\"})"
    }
   ]
  },
  {
   "title": "Read Throughput",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(eos_space_disk_readratemb{cluster=\"eos$instance\"})"
    }
   ]
  },
  {
   "title": "Avg Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "avg(eos.$instance.ns_latency.*.*)"
    }
   ]
  },
  {
   "title": "UpTime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eos_ns_uptime_seconds{cluster=\"eos$instance\"}"
    }
   ]
  },
  {
   "title": "Recycle bin fill",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eos_recycle_used_bytes{cluster=\"eos$instance\"} / eos_recycle_max_bytes{cluster=\"eos$instance\"}"
    }
   ]
  },
  {
   "title": "Avg Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_time_seconds{job=\"node\", eosinstance=\"$instance\", role=\"storage\"} - node_boot_time_seconds{job=\"node\", eosinstance=\"$instance\", role=\"storage\"})"
    }
   ]
  },
  {
   "title": "MGM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"node\", eosinstance=\"$instance\", role=\"ns\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "FST",
   "type": "stat",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"node\", eosinstance=\"$instance\", role=\"storage\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Files opened R/W",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(eos_space_disk_ropen{cluster=\"eos$instance\"})",
     "legendFormat": "read"
    },
    {
     "expr": "sum(eos_space_disk_wopen{cluster=\"eos$instance\"})",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "EOS Total IO",
   "type": "timeseries",
   "description": "User Traffic",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "sum(eos_space_disk_writeratemb{cluster=\"eos$instance\"})",
     "legendFormat": "write"
    },
    {
     "expr": "sum(eos_space_disk_readratemb{cluster=\"eos$instance\"})",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "Aggregated Disk IO",
   "type": "timeseries",
   "description": "User Traffic + Background Scrubbing: sum(reads+writes)",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "sum(eos_space_disk_readratemb{cluster=\"eos$instance\"})",
     "legendFormat": "read"
    },
    {
     "expr": "sum(eos_space_disk_writeratemb{cluster=\"eos$instance\"})",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Batch traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(eos_io_app_out_bytes{cluster=\"eos$instance\", app=\"fuse::bi\"}[5m])",
     "legendFormat": "OUT"
    },
    {
     "expr": "-rate(eos_io_app_in_bytes{cluster=\"eos$instance\", app=\"fuse::bi\"}[5m])",
     "legendFormat": "IN"
    }
   ]
  },
  {
   "title": "Fuse IN",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(eos_io_app_in_bytes{cluster=\"eos$instance\",app=~\"fuse:.*\"}[5m])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Fuse  OUT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(eos_io_app_out_bytes{cluster=\"eos$instance\", app=~\"fuse:.*\"}[5m])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "IN  per app",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (app)(rate(eos_io_app_in_bytes{cluster=\"eos$instance\"}[5m]))",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "OUT  per app",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (app)(rate(eos_io_app_out_bytes{cluster=\"eos$instance\"}[5m]))",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "EOS Internal",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(eos_io_app_in_bytes{app=~\"eos/.*|groupbalancer\", cluster=\"eos$instance\"}[5m]) + rate(eos_io_app_out_bytes{app=~\"eos/.*|groupbalancer\", cluster=\"eos$instance\"}[5m])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Directories and files",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "eos_ns_files_total{cluster=\"eos$instance\"}",
     "legendFormat": "files"
    },
    {
     "expr": "eos_ns_dirs_total{cluster=\"eos$instance\"}",
     "legendFormat": "directories"
    }
   ]
  },
  {
   "title": "Free Space (Default, RAW)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "eos_space_statfs_freebytes_configrw{space=\"default\", cluster=\"eos$instance\"}",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "Socket Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_sockstat_sockets_used{eosinstance=\"${instance}\", role=\"ns\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "EOS Connections Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(eos_who{cluster=\"eos$instance\", gateway=~\"b7.*\"})",
     "legendFormat": "batch"
    },
    {
     "expr": "sum(eos_who{cluster=\"eos$instance\", gateway=~\"lxplus.*\"})",
     "legendFormat": "lxplus"
    },
    {
     "expr": "sum(eos_who{cluster=\"eos$instance\", gateway!~\"lxplus.*|b7.*|.*node-.*|.*lbproxy.*|.*:.*|paas-.*|.*-master-.*|standard-.*|st-home.*|eosfst-.*|p0.*|cback-.*|.*ocis.*|.*lbweb.*|.*lbeosgw.*|.*samba.*|.*fts.*\"})",
     "legendFormat": "other"
    },
    {
     "expr": "sum(eos_who{cluster=\"eos$instance\", gateway=~\".*node-.*|.*-master-.*\"})",
     "legendFormat": "k8s"
    },
    {
     "expr": "sum(eos_who{cluster=\"eos$instance\", gateway=~\".*lbproxy.*|.*lbeosgw.*\"})",
     "legendFormat": "sync client"
    },
    {
     "expr": "sum(eos_who{cluster=\"eos$instance\", gateway=~\"paas-.*|standard-.*\"})",
     "legendFormat": "openshift"
    },
    {
     "expr": "sum(eos_who{cluster=\"eos$instance\", gateway=~\"st-home.*|eosfst-.*|p0.*\"})",
     "legendFormat": "fst"
    },
    {
     "expr": "sum(eos_who{cluster=\"eos$instance\", gateway=~\"cback-.*\"})",
     "legendFormat": "cback"
    },
    {
     "expr": "sum(eos_who{cluster=\"eos$instance\", gateway=~\".*ocis.*|.*lbweb.*\"})",
     "legendFormat": "web"
    },
    {
     "expr": "sum(eos_who{cluster=\"eos$instance\", gateway=~\".*samba.*\"})",
     "legendFormat": "samba"
    },
    {
     "expr": "sum(eos_who{cluster=\"eos$instance\", gateway=~\".*fts.*\"})",
     "legendFormat": "fts"
    }
   ]
  },
  {
   "title": "EOS Connections Summary",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(eos_who{cluster=\"eos$instance\", gateway=~\"b7.*\"})",
     "legendFormat": "batch"
    },
    {
     "expr": "sum(eos_who{cluster=\"eos$instance\", gateway=~\"lxplus.*\"})",
     "legendFormat": "lxplus"
    },
    {
     "expr": "sum(eos_who{cluster=\"eos$instance\", gateway!~\"lxplus.*|b7.*|.*node-.*|.*lbproxy.*|.*:.*|paas-.*|.*-master-.*|standard-.*|st-home.*|eosfst-.*|p0.*|cback-.*|.*ocis.*|.*lbweb.*|.*lbeosgw.*|.*samba.*|.*fts.*\"})",
     "legendFormat": "other"
    },
    {
     "expr": "sum(eos_who{cluster=\"eos$instance\", gateway=~\".*node-.*|.*-master-.*\"})",
     "legendFormat": "k8s"
    },
    {
     "expr": "sum(eos_who{cluster=\"eos$instance\", gateway=~\".*lbproxy.*|.*lbeosgw.*\"})",
     "legendFormat": "sync client"
    },
    {
     "expr": "sum(eos_who{cluster=\"eos$instance\", gateway=~\"paas-.*|standard-.*\"})",
     "legendFormat": "openshift"
    },
    {
     "expr": "sum(eos_who{cluster=\"eos$instance\", gateway=~\"st-home.*|eosfst-.*|p0.*\"})",
     "legendFormat": "fst"
    },
    {
     "expr": "sum(eos_who{cluster=\"eos$instance\", gateway=~\"cback-.*\"})",
     "legendFormat": "cback"
    },
    {
     "expr": "sum(eos_who{cluster=\"eos$instance\", gateway=~\".*ocis.*|.*lbweb.*\"})",
     "legendFormat": "web"
    },
    {
     "expr": "sum(eos_who{cluster=\"eos$instance\", gateway=~\".*samba.*\"})",
     "legendFormat": "samba"
    },
    {
     "expr": "sum(eos_who{cluster=\"eos$instance\", gateway=~\".*fts.*\"})",
     "legendFormat": "fts"
    }
   ]
  },
  {
   "title": "File/Dir deletion rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "rate(eos_ns_stat_sum_total{operation=\"Rm\", cluster=\"eos$instance\"}[5m])",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "rate(eos_ns_stat_sum_total{operation=\"RmDir\", cluster=\"eos$instance\"}[5m])",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Number of threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "eos_ns_threads_total{cluster=\"eos$instance\"}",
     "legendFormat": "threads"
    }
   ]
  },
  {
   "title": "Recycle Bin Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "eos_recycle_max_bytes{cluster=\"eos$instance\"}\n",
     "legendFormat": "Max"
    },
    {
     "expr": "eos_recycle_used_bytes{cluster=\"eos$instance\"}\n",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Thread Stalls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "rate(eos_ns_stat_sum_total{cluster=\"eos$instance\", operation=~\"Stall::threads::.*\"}[5m])",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  { "title": "Namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Namespace cache - files",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "eos_ns_cache_files_occ_total{cluster=\"eos$instance\"}",
     "legendFormat": "files"
    },
    {
     "expr": "eos_ns_cache_files_total{cluster=\"eos$instance\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Namespace cache - directories",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 67 },
   "targets": [
    {
     "expr": "eos_ns_cache_container_occ_total{cluster=\"eos$instance\"}",
     "legendFormat": "directories"
    },
    {
     "expr": "eos_ns_cache_container_max_total{cluster=\"eos$instance\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "File descriptors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "eos_ns_fds_total{cluster=\"eos$instance\"}",
     "legendFormat": "EOS fds"
    },
    {
     "expr": "node_filefd_allocated{eosinstance=\"$instance\", role=\"ns\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(uid)(eos_who{cluster=\"eos$instance\", uid!~\"nobody|eosnobody|daemon\"}) > 25",
     "legendFormat": "HappyUser :)"
    }
   ]
  },
  {
   "title": "Top Namespace Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(10, rate(eos_ns_stat_sum_total{cluster=\"eos$instance\"}[5m]))",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "rate(eos_ns_stat_sum_total{cluster=\"eos$instance\", operation=\"Eosxd::int::ValidatePERM\"}[5m])",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Namspace Nodes Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-(node_memory_MemAvailable_bytes/node_memory_MemTotal_bytes{eosinstance=\"$instance\", role=\"ns\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Namspace nodes CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{eosinstance=\"$instance\", role=\"ns\", mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "Namespace latency",
   "type": "timeseries",
   "description": "duration of simple namespace-only operations (eos mkdir, eos rmdir, eos touch, eos rm), in sec.\nnegative value: command returned an error.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "aliasByNode(eos.$instance.ns_latency.*.*, 4)"
    }
   ]
  },
  {
   "title": "Peak Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "eos_ns_lat_eosvm_last_seconds{cluster=\"eos${instance}\"}",
     "legendFormat": "last"
    }
   ]
  },
  {
   "title": "Stall Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 91 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scaleToSeconds(exclude(nonNegativeDerivative(sumSeriesWithWildcards(eos.$instance.ns_ops.Stall::OpenRead, 1)), 'Hash'), 1), 2)"
    },
    {
     "target": "aliasByNode(scaleToSeconds(exclude(nonNegativeDerivative(sumSeriesWithWildcards(eos.$instance.ns_ops.Stall::Open, 1)), 'Hash'), 1), 2)"
    },
    {
     "target": "aliasByNode(scaleToSeconds(exclude(nonNegativeDerivative(sumSeriesWithWildcards(eos.$instance.ns_ops.Stall::OpenWrite, 1)), 'Hash'), 1), 2)"
    },
    {
     "target": "aliasByNode(scaleToSeconds(exclude(nonNegativeDerivative(sumSeriesWithWildcards(eos.$instance.ns_ops.Stall::OpenDir-Entry, 1)), 'Hash'), 1), 2)"
    },
    {
     "target": "aliasByNode(scaleToSeconds(exclude(nonNegativeDerivative(sumSeriesWithWildcards(eos.$instance.ns_ops.Stall::Rm, 1)), 'Hash'), 1), 2)"
    }
   ]
  },
  {
   "title": "dd_4m_dsync_ms",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 97 },
   "repeat": "microtest",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode(removeAbovePercentile(eos.clients.fuse.$instance.microtests.dd_4m_dsync_ms, 99), 5)"
    }
   ]
  },
  {
   "title": "create_repo_ms",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode(removeAbovePercentile(eos.clients.fuse.$instance.microtests.createrepo_ms, 99), 5)"
    }
   ]
  },
  {
   "title": "git_clone_ms",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode(removeAbovePercentile(eos.clients.fuse.$instance.microtests.git_clone_ms, 99), 5)"
    }
   ]
  },
  { "title": "Fusex", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 } },
  {
   "title": "Fusex clients",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "eos_ns_fusex_clients_total{cluster=\"eos$instance\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "eos_ns_fusex_clients_total{cluster=\"eos$instance\"}-eos_ns_fusex_activeclients_total{cluster=\"eos$instance\"}",
     "legendFormat": "Inactive"
    },
    {
     "expr": "eos_ns_fusex_locked_clients_total{cluster=\"eos$instance\"}",
     "legendFormat": "Locked"
    }
   ]
  },
  {
   "title": "Fusex caps",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "eos_ns_fusex_caps_total{cluster=\"eos$instance\"}",
     "legendFormat": "caps"
    }
   ]
  },
  { "title": "Group Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 } },
  {
   "title": "Group Avg Filled",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eos_group_statfs_filled_avg{cluster=\"eos$instance\"}",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Group  Filled Dev",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eos_group_statfs_filled_dev{cluster=\"eos$instance\"}",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Group Filled Avg",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 120 },
   "targets": [
    {
     "expr": "eos_group_statfs_filled_avg{cluster=\"eos$instance\", group=~\"default.*\"}",
     "legendFormat": "{{group}}"
    }
   ]
  },
  { "title": "FS Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 130 } },
  {
   "title": "FS Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 131 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(eos_fs_status{cluster=\"eos$instance\"} == 1)",
     "legendFormat": "online"
    },
    {
     "expr": "count(eos_fs_status{cluster=\"eos$instance\"} == 0) or vector(0)",
     "legendFormat": "offline"
    }
   ]
  },
  {
   "title": "FS Boot Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 4, "y": 131 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(eos_fs_boot_status{cluster=\"eos$instance\"} == 0) or vector(0)",
     "legendFormat": "booted"
    },
    {
     "expr": "count(eos_fs_boot_status{cluster=\"eos$instance\"} == 1) or vector(0)",
     "legendFormat": "booting"
    },
    {
     "expr": "count(eos_fs_boot_status{cluster=\"eos$instance\"} == 2) or vector(0)",
     "legendFormat": "bootfailure"
    },
    {
     "expr": "count(eos_fs_boot_status{cluster=\"eos$instance\"} == 3) or vector(0)",
     "legendFormat": "opserror"
    },
    {
     "expr": "count(eos_fs_boot_status{cluster=\"eos$instance\"} == 4) or vector(0)",
     "legendFormat": "down"
    }
   ]
  },
  {
   "title": "FS Config Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 131 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(eos_fs_config_status{cluster=\"eos$instance\"} == 0) or vector(0)",
     "legendFormat": "configstatus=rw"
    },
    {
     "expr": "count(eos_fs_config_status{cluster=\"eos$instance\"} == 1) or vector(0)",
     "legendFormat": "configstatus=ro"
    },
    {
     "expr": "count(eos_fs_config_status{cluster=\"eos$instance\"} == 2) or vector(0)",
     "legendFormat": "configstatus=drain"
    },
    {
     "expr": "count(eos_fs_config_status{cluster=\"eos$instance\"} == 3) or vector(0)",
     "legendFormat": "configstatus=empty"
    }
   ]
  },
  {
   "title": "FST - Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"node\", eosinstance=\"$instance\", role=\"storage\"} - node_boot_time_seconds{job=\"node\", eosinstance=\"$instance\", role=\"storage\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Avg Fill",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(node)(eos_fs_statfs_usedbytes{cluster=\"eos$instance\"})/sum by(node)(eos_fs_statfs_sizebytes{cluster=\"eos$instance\"})",
     "legendFormat": "{{fsid}}"
    }
   ]
  },
  { "title": "Node Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 145 } },
  {
   "title": "Node Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 146 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(eos_fs_status{cluster=\"eos$instance\"} == 1) or vector(0)",
     "legendFormat": "online"
    },
    {
     "expr": "count(eos_fs_status{cluster=\"eos$instance\"} == 0) or vector(0)",
     "legendFormat": "offline"
    }
   ]
  },
  {
   "title": "Node Avg Fill",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 11, "x": 3, "y": 146 },
   "targets": [
    {
     "expr": "sum by(node)(eos_fs_statfs_usedbytes{cluster=\"eos$instance\"})/sum by(node)(eos_fs_statfs_sizebytes{cluster=\"eos$instance\"})*100",
     "legendFormat": "{{fsid}}"
    }
   ]
  },
  {
   "title": "Allocated file descriptors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 146 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_filefd_allocated{eosinstance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Read operations distribution",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\nsum by(node)(eos_fs_disk_ropen{cluster=\"eos$instance\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Write operations distribution",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\nsum by(node)(eos_fs_disk_wopen{cluster=\"eos$instance\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Where is the free space? ",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\nsum by(node)(eos_fs_statfs_freebytes{cluster=\"eos$instance\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Read operations distribution",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 162 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "\nsum by(node)(eos_fs_disk_ropen{cluster=\"eos$instance\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "write operations distribution",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 162 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "\nsum by(node)(eos_fs_disk_wopen{cluster=\"eos$instance\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Storage Nodes Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 171 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-(node_memory_MemAvailable_bytes/node_memory_MemTotal_bytes{eosinstance=\"$instance\", role=\"storage\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Storage nodes CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 171 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{eosinstance=\"$instance\", role=\"storage\", mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Avg CPU/Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 171 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (eosinstance) (rate(node_cpu_seconds_total{eosinstance=\"$instance\", role=\"storage\", mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU AVG usage"
    },
    {
     "expr": "avg by (eosinstance)(1-(node_memory_MemAvailable_bytes/node_memory_MemTotal_bytes{eosinstance=\"$instance\", role=\"storage\"}))*100",
     "legendFormat": "Mem AVG usage"
    }
   ]
  },
  {
   "title": "ICMP Probe",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 179 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "probe_success{eosinstance=\"$instance\", role=\"storage\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ICMP Probe",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 179 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{eosinstance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network received  bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 186 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(instance)(rate(node_network_receive_bytes_total{eosinstance=\"$instance\", role=\"storage\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Transmitted  bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 186 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(instance)(rate(node_network_transmit_bytes_total{eosinstance=\"$instance\", role=\"storage\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "FSCK", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 194 } },
  {
   "title": "FSCK Stat",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 195 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(tag)(eos_fsck_stat{cluster=\"eos$instance\"})",
     "legendFormat": "{{tag}}"
    }
   ]
  }
 ]
}