---
name: "tagged-release"

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Tagged release test scenario'  

jobs:
  tagged-release:
    name: "Tagged Release"
    #runs-on: "golangci/golangci-lint"
    runs-on: self-hosted

    steps:
      # ...
      - name: "Build & test"
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17.0'
        run: |
          go mod init example.com/m
          go build .
          #make build
          echo "built done!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            eos_exporter
